# Generated by setup_terraform_backend.sh on 2025-05-19 09:24:26
# This file configures the Terraform backend to use S3 for state storage with local file locking

terraform {
  backend "s3" {
    bucket       = "phase2cap-124355645722"
    key          = "terraform.tfstate"
    region       = "eu-west-1"
    encrypt      = true
    use_lockfile = true
  }
}
